positions_dir = "~/s/g/positions"

[exchanges.binance]
api_pubkey = { env = "BINANCE_TIGER_FULL_PUBKEY" }
api_secret = { env = "BINANCE_TIGER_FULL_SECRET" }

[exchanges.bybit]
api_pubkey = { env = "QUANTM_BYBIT_SUB_PUBKEY" }
api_secret = { env = "QUANTM_BYBIT_SUB_SECRET" }

[exchanges.mexc]
api_pubkey = { env = "MEXC_READ_PUBKEY" }
api_secret = { env = "MEXC_READ_SECRET" }

[exchanges.kucoin]
api_pubkey = { env = "KUCOIN_API_PUBKEY" }
api_secret = { env = "KUCOIN_API_SECRET" }
api_passphrase = { env = "KUCOIN_API_PASSPHRASE" }
