[package]
name = "rust_plugins"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.6", features = ["neovim-0-11"] }
chrono = "0.4"
regex = "1"
